### ISSUE TITLE
[OSS] Angular spa project angular-app

### ISSUE THREAD

**Issue by kellishouts** [AirshipCMS/angular-app.airshipcms.io#1]
### Summary
This demo project demonstrates an Airship project that uses the latest version of Angular 4 in a SPA to render all pages.

### Subdomain
angular-app.airshipcms.io
This site exists, and you have been added as a superadmin.

### Github repo
https://github.com/AirshipCMS/angular-app.airshipcms.io

### SPA Routes
{code}[{"pattern":"/.*","destination":"/"}]{code}
You will need to ask Jon to set up.

### Build Tools
use angular-cli and configure it to output the files to compartments

### Templating
Put spa templates in /compartments/assets/scripts/templates/

### Other Compartments
only need layouts/spa.html and templates/root.html

layouts/spa.html should have a content block for 'head' if you need to inject any css styles (although, webpack will probably bundle everything though)
templates/root.html should include all the js from assets/scripts/

### Airship Schema
- Root:  Main page that launches the SPA
- Styling (page)
- Airship Schema (page)
- React Tutorial (page)
the contents describe how the spa app was setup after landing, implementation details, gulp configuration, and the local dev cycle to create and launch this project (tutorial)
- Elements (collection)
For the collection index.html listing page, use react to iterate over the elements to only show thumbnail and name. clicking on one element should go to it's detail page (*still in spa*) that shows all the information.

### Routes
The spa should have the following routes:
- **/** : landing page, `GET /api/pages/__root__` displays root page fields
- **/airship-schema** : airship-schema
- **/styling** : styling tutorial page, `GET /api/pages/styling`, displays body
- **/react-tutorial** : react tutorial page, `GET /api/pages/react-tutorial`, displays body
- **/elements** : elements collection page, `GET /api/pages/elements`, displays list of links to each element
- **/elements/:permalink** : example aerostat detail, `GET /api/collection/elements/view/:permalink`, displays the element fields according to layout

Inside the spa, have some navigation for the first 4 routes. Inside the spa, the title and github link in the header are also rendered by the SPA.

A visitor to this Airship Site should be able to use this project and the github repo as a working example of how to create a spa app that uses Angular 4 compiled with ng cli using airship as a cms.

*Note: it may be difficult finding the best way to configure the ng cli to output and include templates in a way that will work well with airship, you can ask [~jon] for advice, and check out this (unfinished) project https://github.com/AirshipCMS/react-app.airshipcms.io (this is not final, and not the best way to do it)  

### Styling
Style with Angular Red Theme of Bulma.

### Bounty
**$200** for completion of the above.
If edits are needed after initial review, yet the scope is completed, additional tasks for revisions will be created.

**Comment by fobabett** [comment]
starting

**Comment by fobabett** [comment]
done
